# -*- coding: utf-8 -*-
"""caesar_cipher.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zIU2ovh7VXPRcn8pxnIF4N8TeHjnIVat
"""

def encrypt(text, shift):
    result = ""
    for char in text:
        if char.isalpha():
            ascii_offset = ord('a') if char.islower() else ord('A')
            encrypted_char = chr((ord(char) - ascii_offset + shift) % 26 + ascii_offset)
            result += encrypted_char
        else:
            result += char
    return result

text = input("Введите текст на английском. Текст не должен содержать цифры и знаки препинания: ")

# Проверяем, что введенный текст содержит только английские символы и пробелы
while not all(char.isalpha() or char.isspace() for char in text):
    text = input("Введен некорректный текст. Введите текст на английском: ")

shift = input("Введите смещение (целое число): ")

# Проверяем, что введенное смещение - целое число
while not shift.isdigit():
    shift = input("Введен некорректный сдвиг. Введите целое число: ")

shift = int(shift)

encrypted_text = encrypt(text, shift)
print(f"Зашифрованный текст: {encrypted_text}")

